import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const Faqs = () => {
  return (
    <div className="flex flex-col space-y-12">
      <h3 className="text-3xl text-left font-bold uppercase">Faq</h3>
      <div className="flex flex-col space-y-12">
        <Card className="w-full flex flex-col space-y-6 rounded-3xl shadow-lg p-2">
          <CardHeader>
            <CardTitle className="text-xl font-bold">
              How does it Work?
            </CardTitle>
          </CardHeader>
          <CardContent>
            Our website allows students to generate a timetable by importing
            their course registration and timetable PDF files. The generated
            timetable can be edited and exported as a PDF or Google Calendar
            file for maximum efficiency.
          </CardContent>
        </Card>
        <Card className="w-full flex flex-col space-y-6 rounded-3xl shadow-lg p-2">
          <CardHeader>
            <CardTitle className="text-xl font-bold">
              What file formats are supported?
            </CardTitle>
          </CardHeader>
          <CardContent>
            Our website allows students to generate a timetable by importing
            their course registration and timetable PDF files. The generated
            timetable can be edited and exported as a PDF or Google Calendar
            file for maximum efficiency.
          </CardContent>
        </Card>
        <Card className="w-full flex flex-col space-y-6 rounded-3xl shadow-lg p-2">
          <CardHeader>
            <CardTitle className="text-xl font-bold">
              How can I contact you?
            </CardTitle>
          </CardHeader>
          <CardContent>
            If you have any further questions or require assistance with
            anything at all, please feel free to reach out to our dedicated
            support team. We are available to help you with any concerns or
            inquiries you may have.
          </CardContent>
        </Card>
        <Card className="w-full flex flex-col space-y-6 rounded-3xl shadow-lg p-2">
          <CardHeader>
            <CardTitle className="text-xl font-bold">
              Can I edit the generated timetable?
            </CardTitle>
          </CardHeader>
          <CardContent>
            Yes, you can easily make edits to the timetable that is generated by
            our website. You have the flexibility to adjust and customize it
            based on your specific preferences and requirements.
          </CardContent>
        </Card>
      </div>
    </div>
  );
};
